WeatherApp/urls.py
from django.contrib import admin
from django.urls import path, include
from weather.views import index, start
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', start, name='start'),
    path('weather/', include('weather.urls',namespace = 'weather'))
]

weather/urls.py
# WeatherApp.urls

from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:name_city>/', views.get_curr_info, name='weather-detail'),
    path('<str:name_city>/delete/', views.DeleteCurWR.as_view(), name='del_weather'),
    path('1/<str:name_city>/', views.get_info_1, name='weather_ch1'),
    path('2/<str:name_city>/', views.get_info_2, name='weather_ch2'),
    path('3/<str:name_city>/', views.get_info_3, name='weather_ch3'),
]

weather/models.py
# models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=300)

    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} | {self.id}'

weather/forms.py
from .models import City
from django.forms import ModelForm, TextInput

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ["name"]
        widgets = {'name' : TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : "Город",
            'id' : "cityInput"
        })}

weather/views.py
import requests
from django.shortcuts import render
from .models import City
from .forms import CityForm
from django.contrib import messages
from django.views.generic.edit import DeleteView
from django.http import HttpResponseNotFound
from django.urls import reverse_lazy

import pytz
from datetime import datetime
t = pytz.timezone('Europe/Moscow')
moscow_current_datetime = str(datetime.today()).split()

global API_key, url_1, url_2
API_key = '795e457b87c6d307d19165ae3f930411'
url_1 = "https://api.openweathermap.org/data/2.5/weather?q={}&appid=" + API_key + '&units=metric' + '&lang=ru'
url_2 = "https://api.openweathermap.org/data/2.5/forecast?q={}&appid=" + API_key + '&units=metric' + '&lang=ru' +'&cnt=35'

def get_curr_info(request, name_city):

    glavn = []

    if  len(City.objects.filter(name=name_city)) == 0:
        return HttpResponseNotFound("Город не существует!")
    res2 = requests.get(url_2.format(name_city)).json()
    data = ""
    for i in res2['list']:
        dt = dict()
        if moscow_current_datetime[0] == i['dt_txt'].split()[0]:
            dt['time'] = i['dt_txt'].split()[1][:-3]
            dt['descr'] = i['weather'][0]['description']
            dt['temp'] = i['main']['temp']
            dt['icon'] = i['weather'][0]['icon']
            glavn.append(dt)
            data = i['dt_txt'].split()[0][-2:] + i['dt_txt'].split()[0][-6:-2] + i['dt_txt'].split()[0][:4]
        elif moscow_current_datetime[0] > i['dt_txt'].split()[0]:
            continue
        else:

            break

    context = {'city' : name_city,
                'all_dt' : glavn,
                'date' : data,
                }
    return render(request, 'weather/weather_view.html', context)

def get_info_1(request, name_city):

    glavn = []

    if  len(City.objects.filter(name=name_city)) == 0:
        return HttpResponseNotFound("Город не существует!")
    res2 = requests.get(url_2.format(name_city)).json()

    k = 0
    need = moscow_current_datetime[0]
    data = ""
    for i in res2['list']:
        dt = dict()
        if need == i['dt_txt'].split()[0] and k == 1:
            dt['time'] = i['dt_txt'].split()[1][:-3]
            dt['descr'] = i['weather'][0]['description']
            dt['temp'] = i['main']['temp']
            dt['icon'] = i['weather'][0]['icon']
            glavn.append(dt)
        elif need < i['dt_txt'].split()[0]:
            k += 1
            if k == 1:
                data = i['dt_txt'].split()[0][-2:] + i['dt_txt'].split()[0][-6:-2] + i['dt_txt'].split()[0][:4]
                dt['time'] = i['dt_txt'].split()[1][:-3]
                dt['descr'] = i['weather'][0]['description']
                dt['temp'] = i['main']['temp']
                dt['icon'] = i['weather'][0]['icon']

                glavn.append(dt)

                need = i['dt_txt'].split()[0]
            else:
                break

    context = {'city' : name_city,
                'all_dt' : glavn,
                'date' : data,
                }
    return render(request, 'weather/weather_view.html', context)

def get_info_2(request, name_city):

    glavn = []

    if  len(City.objects.filter(name=name_city)) == 0:
        return HttpResponseNotFound("Город не существует!")
    res2 = requests.get(url_2.format(name_city)).json()

    k = 0
    need = moscow_current_datetime[0]
    data = ""
    for i in res2['list']:
        dt = dict()
        if need == i['dt_txt'].split()[0] and k == 2:
            dt['time'] = i['dt_txt'].split()[1][:-3]
            dt['descr'] = i['weather'][0]['description']
            dt['temp'] = i['main']['temp']
            dt['icon'] = i['weather'][0]['icon']
            glavn.append(dt)
        elif need < i['dt_txt'].split()[0]:
            k += 1
            need = i['dt_txt'].split()[0]
            if k == 2:
                data = i['dt_txt'].split()[0][-2:] + i['dt_txt'].split()[0][-6:-2] + i['dt_txt'].split()[0][:4]
                dt['time'] = i['dt_txt'].split()[1][:-3]
                dt['descr'] = i['weather'][0]['description']
                dt['temp'] = i['main']['temp']
                dt['icon'] = i['weather'][0]['icon']

                glavn.append(dt)
            elif k == 3:
                break

    context = {'city' : name_city,
                'all_dt' : glavn,
                'date' : data,
                }
    return render(request, 'weather/weather_view.html', context)

def get_info_3(request, name_city):

    glavn = []

    if  len(City.objects.filter(name=name_city)) == 0:
        return HttpResponseNotFound("Город не существует!")
    res2 = requests.get(url_2.format(name_city)).json()

    k = 0
    need = moscow_current_datetime[0]
    data = ""
    for i in res2['list']:
        dt = dict()
        if need == i['dt_txt'].split()[0] and k == 3:
            dt['time'] = i['dt_txt'].split()[1][:-3]
            dt['descr'] = i['weather'][0]['description']
            dt['temp'] = i['main']['temp']
            dt['icon'] = i['weather'][0]['icon']
            glavn.append(dt)
        elif need < i['dt_txt'].split()[0]:
            k += 1
            need = i['dt_txt'].split()[0]
            if k == 3:
                data = i['dt_txt'].split()[0][-2:] + i['dt_txt'].split()[0][-6:-2] + i['dt_txt'].split()[0][:4]
                dt['time'] = i['dt_txt'].split()[1][:-3]
                dt['descr'] = i['weather'][0]['description']
                dt['temp'] = i['main']['temp']
                dt['icon'] = i['weather'][0]['icon']

                glavn.append(dt)
            elif k == 4:
                break

    context = {'city' : name_city,
                'all_dt' : glavn,
                'date' : data,
                }
    return render(request, 'weather/weather_view.html', context)

class DeleteCurWR(DeleteView):
    model = City
    template_name = 'weather/index.html'
    success_url = reverse_lazy('weather:index')  # Redirect to the 'index' view

    def get_object(self, queryset=None):
        # Retrieve the City object based on the name_city parameter in the URL
        return self.model.objects.get(name=self.kwargs['name_city'])

def start(request):
    context = {'title' : 'Welcome!'}
    return render(request, 'weather/start.html', context)

def index(request):
    flag_err = False
    flag_post = False

    if request.method=="POST":
        form_p = CityForm(request.POST)
        flag_post = True
        form_p.save()
    
    form_p = CityForm()

    if len(City.objects.all()) > 5:
        City.objects.last().delete()
        flag_err = True
        mess = 'Максимум можно отслеживать 5 городов!'
            
    cities = City.objects.all()

    all_cities = []

    for city in cities:

        res1 = requests.get(url_1.format(city.name)).json()
        res2 = requests.get(url_2.format(city.name)).json()
        if res1['cod'] == 200:
        
            city_info = {
                'city' : city.name,
                'temp' : round(res1['main']['temp']),
                "icon" : res1['weather'][0]['icon'],
                'wind' : round(res1['wind']['speed'], 1),
            }
            
            count = 0
            max_temp = -100
            icon = ""
            dat = ""
            list_dt = []
            for i in range(res2['cnt']):
                if  (moscow_current_datetime[0]) < (res2['list'][i]['dt_txt'].split()[0]):
                    if res2['list'][i]['dt_txt'].split()[0][-2:] not in list_dt:
                        if len(list_dt) > 0:
                            city_info['temp_' + str(count)] = max_temp
                            city_info['icon_' + str(count)] = icon
                            city_info['time_' + str(count)] = dat
                        list_dt.append(res2['list'][i]['dt_txt'].split()[0][-2:])
                        dat = ".".join([res2['list'][i]['dt_txt'].split()[0][-2:], res2['list'][i]['dt_txt'].split()[0][-5:-3]])
                        
                        count += 1
                        if count == 4:
                            break
                        max_temp = -100
                        icon = ""

                    if res2['list'][i]['main']['temp'] > max_temp:
                        max_temp = round(res2['list'][i]['main']['temp'])
                        icon = res2['list'][i]['weather'][0]['icon']
  

            if city_info in all_cities:
                City.objects.last().delete()
                flag_err = True
                mess = 'Город уже был!'
            else:
                all_cities.append(city_info)
        else:
            City.objects.last().delete()
            flag_err = True
            mess = "Введите правильное название города!"
            
    if flag_err and flag_post:
        messages.error(request, mess)
    elif flag_post and (not flag_err):
        messages.success(request, "Город добавлен!")

    context = {'all_form' : all_cities, 'form' : form_p}
    return render(request, 'weather/index.html', context)

weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Погодное приложение</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a href="{% url 'weather:index' %}" class="navbar-brand">
                <strong>Weather report</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>

    <div class="container mt-5">
        <h1>Какой город узнать?</h1>
        
        <div class="row">
            <div class="col-md-6">       
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        {{ form.name }}
                    </div>
                    {% if messages %}
                        {% for msg in messages %}
                            <div class="alert {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert">
                                {{ msg }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <input type="submit" value="Узнать" class="btn btn-primary rounded-pill px-3">
                </form>
            </div>
            {% include 'weather/table_info.html' %}
        </div>
    </div>
</body>
</html>

weather/templates/weather/start.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <style>
        body {
            background-image: url('https://ru.nencom.com/uf/pre/c8dd6154eb7020e8cc3.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

        .jumbotron {
            background-color: #007bff;
            color: #ffffff;
            padding: 2rem 1rem;
        }

        .description {
            font-size: 1.2rem;
            margin-top: 2rem;
        }

        .btn-get-started {
            background-color: #007bff;
            color: #ffffff;
            border: none;
            padding: 10px 20px;
            font-size: 1.2rem;
            text-decoration: none;
        }

        .btn-get-started:hover {
            background-color: #0056b3;
            color: #ffffff;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a href="{% url 'weather:index' %}" class="navbar-brand">
                <strong>Weather report</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>

    <div class="jumbotron text-center">
        <h1 class="display-4">Добро пожаловать на наш сайт!</h1>
        <p class="lead">Узнайте текущую погоду в интересующем вас городе.</p>
        <a href="{% url 'weather:index' %}" class="btn btn-get-started">Узнать погоду</a>
    </div>

    <!-- The rest of your landing page content can be inserted here -->
</body>
</html>

weather/templates/weather/table_info.html
{% if all_form %}
            <div class="col-md-6">
                <h2 class="mt-0">Меню городов:</h2>
                {% for form_ab in all_form %}
                <div class="alert alert-primary" role="alert">
                    <div class="row">
                        <div class="col-md-2">
                            <a href="{% url 'weather:weather-detail' form_ab.city  %}">
                                <img src="https://openweathermap.org/img/w/{{ form_ab.icon }}.png" alt="Погода" class="img-thumbnail">
                            </a>
                        </div>
                        <div class="col-md-9">
                            <div class="row">
                                <div class="col-md-6">
                                    <b>Город:</b> {{ form_ab.city }}<br>
                                    <b>Температура:</b> {{ form_ab.temp }}°C<br>
                                    <b>Скорость ветра:</b> {{ form_ab.wind }} м/с<br>
                                </div>
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <b>{{ form_ab.time_1 }}</b>
                                            <a href="{% url 'weather:weather_ch1' form_ab.city  %}">
                                                <img src="https://openweathermap.org/img/w/{{ form_ab.icon_1 }}.png" alt="Изображение1" class="img-thumbnail">
                                            </a>
                                            <br>
                                            <b>{{ form_ab.temp_1 }}°C</b> 
                                        </div>
                                        <div class="col-md-4">
                                            <b>{{ form_ab.time_2 }}</b>
                                            <a href="{% url 'weather:weather_ch2' form_ab.city  %}">
                                                <img src="https://openweathermap.org/img/w/{{ form_ab.icon_2 }}.png" alt="Изображение2" class="img-thumbnail">
                                            </a>
                                            <br>
                                            <b>{{ form_ab.temp_2 }}°C</b> 
                                        </div>
                                        <div class="col-md-4">
                                            <b>{{ form_ab.time_3 }}</b>
                                            <a href="{% url 'weather:weather_ch3' form_ab.city  %}">
                                                <img src="https://openweathermap.org/img/w/{{ form_ab.icon_3 }}.png" alt="Изображение3" class="img-thumbnail">
                                            </a>
                                            <br>
                                            <b>{{ form_ab.temp_3 }}°C</b> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-1">
                            <form action="{% url 'weather:del_weather' form_ab.city %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-danger btn-sm" aria-label="Delete city">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </form>
                        </div>
                        
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

weather/templates/weather/weather_view.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ city }} Weather</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a href="{% url 'weather:index' %}" class="navbar-brand">
                <strong>Weather report</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>

    <div class="container mt-4">
        <h1 class="text-center">Погода {{ city }} на {{ date }}</h1>

<div class="row justify-content-center">
    {% for data in all_dt %}
        <div class="col-md-4 mb-4">
            <div class="card text-center">
                <div class="card-header">
                    {{ data.time }}
                </div>
                <div class="card-body">
                    <img src="https://openweathermap.org/img/w/{{ data.icon }}.png" alt="Weather Icon" width="50" height="50"> <!-- Weather Icon in the row with description and temperature -->
                    <h5 class="card-title">{{ data.descr }}</h5>
                    <p class="card-text">Температура: {{ data.temp }}°C</p>
                </div>
            </div>
        </div>
    {% endfor %}

</div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>